"""Tests for shared/encryption.py — 11 cases including cross-language fixture."""

import json
from pathlib import Path

import pytest

from shared.encryption import decrypt, encrypt

# Fixed 64-char hex key used for most tests — not a real secret, test-only.
_TEST_KEY = "0" * 64

# Path to committed cross-language fixtures generated by the TS script.
_FIXTURES_DIR = Path(__file__).parent / "fixtures"


# ---------------------------------------------------------------------------
# Round-trip tests
# ---------------------------------------------------------------------------


def test_roundtrip_empty_string(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setenv("ENCRYPTION_KEY", _TEST_KEY)
    assert decrypt(encrypt("")) == ""


def test_roundtrip_ascii(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setenv("ENCRYPTION_KEY", _TEST_KEY)
    plaintext = "Hello, ROA!"
    assert decrypt(encrypt(plaintext)) == plaintext


def test_roundtrip_unicode(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setenv("ENCRYPTION_KEY", _TEST_KEY)
    plaintext = "Héllo wörld — 🦊🔐"
    assert decrypt(encrypt(plaintext)) == plaintext


def test_roundtrip_long(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setenv("ENCRYPTION_KEY", _TEST_KEY)
    plaintext = "x" * 10_240  # ~10 KB
    assert decrypt(encrypt(plaintext)) == plaintext


# ---------------------------------------------------------------------------
# IV uniqueness
# ---------------------------------------------------------------------------


def test_iv_is_unique(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setenv("ENCRYPTION_KEY", _TEST_KEY)
    result1 = encrypt("same")
    result2 = encrypt("same")
    iv1 = result1[:12]
    iv2 = result2[:12]
    assert iv1 != iv2, "IVs must be random and unique across calls"


# ---------------------------------------------------------------------------
# Byte layout
# ---------------------------------------------------------------------------


def test_byte_layout(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setenv("ENCRYPTION_KEY", _TEST_KEY)
    plaintext = "layout"
    plaintext_bytes = plaintext.encode("utf-8")
    result = encrypt(plaintext)
    expected_len = 28 + len(plaintext_bytes)  # IV(12) + tag(16) + ciphertext(N)
    assert len(result) == expected_len, f"Expected {expected_len} bytes, got {len(result)}"


# ---------------------------------------------------------------------------
# Error cases
# ---------------------------------------------------------------------------


def test_decrypt_too_short(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setenv("ENCRYPTION_KEY", _TEST_KEY)
    with pytest.raises(ValueError, match="Invalid encrypted value: buffer too short"):
        decrypt(b"\x00" * 27)


def test_decrypt_tampered_tag(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setenv("ENCRYPTION_KEY", _TEST_KEY)
    data = bytearray(encrypt("tamper me"))
    # Flip a bit in the auth tag region (bytes 12–27)
    data[12] ^= 0xFF
    with pytest.raises(ValueError, match="authentication tag mismatch"):
        decrypt(bytes(data))


# ---------------------------------------------------------------------------
# Key loading errors
# ---------------------------------------------------------------------------


def test_missing_env_var(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.delenv("ENCRYPTION_KEY", raising=False)
    with pytest.raises(ValueError, match="ENCRYPTION_KEY environment variable is not set"):
        encrypt("x")


def test_invalid_hex_length(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setenv("ENCRYPTION_KEY", "abc")
    with pytest.raises(
        ValueError,
        match="ENCRYPTION_KEY must be a 64-character hex string \\(32 bytes\\)",
    ):
        encrypt("x")


# ---------------------------------------------------------------------------
# Cross-language fixture — THE critical test
# ---------------------------------------------------------------------------


def test_cross_language_fixture_decrypt(monkeypatch: pytest.MonkeyPatch) -> None:
    """Python must decrypt bytes produced by Node.js crypto.

    Reads ts_encrypted.bin and ts_encrypted_meta.json from the fixtures dir,
    sets ENCRYPTION_KEY from the meta file, and asserts the decrypted value
    matches the recorded plaintext.
    """
    bin_path = _FIXTURES_DIR / "ts_encrypted.bin"
    meta_path = _FIXTURES_DIR / "ts_encrypted_meta.json"

    assert bin_path.exists(), f"Missing fixture: {bin_path}"
    assert meta_path.exists(), f"Missing fixture: {meta_path}"

    meta = json.loads(meta_path.read_text(encoding="utf-8"))
    key_hex: str = meta["key_hex"]
    expected_plaintext: str = meta["plaintext"]

    monkeypatch.setenv("ENCRYPTION_KEY", key_hex)

    encrypted_bytes = bin_path.read_bytes()
    result = decrypt(encrypted_bytes)

    assert result == expected_plaintext
